Change HIP_PLATFORM from HCC to AMD and NVCC to NVIDIA
libocca/occa pull request #713
Opened 2023-10-31 15:21 UTC by rakesroy

## Description
- In ROCm6.0 HIP runtime is removing HCC, NVCC symbols
- Replace \_\_HIP_PLATFORM_HCC__ with \_\_HIP_PLATFORM_AMD__
- Replace \_\_HIP_PLATFORM_NVCC__ with \_\_HIP_PLATFORM_NVIDIA__

2023-10-31 15:25 UTC, noelchalmers requested changes
Thanks for the contribution! I'm seeing everything get changed in place to the new namings, but it would be preferable to keep backward compatibility with older ROCm installs. Do you know what the oldest ROCm version is that supports these new names?

2023-11-02 09:19 UTC, rakesroy commented
Hi @noelchalmers,
The new names are supported from ROCm 4.2 onwards. See https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.2.x/include/hip/hip_runtime.h#L59 . We are only removing the deprecated __HIP_PLATFORM_HCC__ & __HIP_PLATFORM_NVCC__ in ROCm 6.0 giving users time of almost 2 major releases to migrate to the new macro.
So unless you require libocca to work with ROCm 4.1 or earlier you should be good with just __HIP_PLATFORM_AMD_ & __HIP_PLATFORM_NVIDIA___.

2023-11-02 17:09 UTC, noelchalmers commented
Thanks for the clarification. In the OCCA README we call our HIP (i.e. ROCm) v3.5 or later is supported. I think it's reasonable to bump this to v4.2. 

I'll merge this PR in and make a separate PR to change the version requirement in the README, as well as clean up some places where we are doing some reverse-compatibility switches for ROCm 3.5.

2023-11-02 17:10 UTC, noelchalmers approved these changes

2023-11-02 17:19 UTC, merged